uo:
    image: ubikz/docker-uo
    volumes:
      - /srv/docker/uo/datafiles:/srv/docker/uo/datafiles
      - /srv/docker/uo/lock:/srv/docker/uo/lock
      - /srv/docker/uo/save:/runuo-master/Saves
    ports:
        - "2593:2593"
    env_file: uo/.env.conf
