nginx:
  image: ubikz/docker-uo-nginx
  links:
    - uo-server:uo-server
  ports:
      - "80:80"
      - "443:443"
  volumes:
      - /srv/docker/nginx/log:/var/log/nginx
  env_file: nginx/.env.conf
uo-server:
  image: ubikz/docker-uo
  volumes:
    - /srv/docker/uo/datafiles:/srv/docker/uo/datafiles
    - /srv/docker/uo/lock:/srv/docker/uo/lock
    - /srv/docker/uo/save:/runuo-master/Saves
    - /srv/docker/uo/backups:/runuo-master/Backups
  ports:
      - "2593:2593"
  env_file: uo/.env.conf
